---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(tidyverse)
library(rlang)
library(ggthemes)
library(scales)
```

# viskit

<!-- badges: start -->
<!-- badges: end -->

The goal of viskit is to make visualizations with ggplot quick and easy

## Installation

You can install the development version of viskit from https://github.com/aengels-git/viskit with:

``` r
# install.packages("devtools")
devtools::install_github("aengels-git/viskit")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(viskit)
tab<-diamonds%>%group_by(cut)%>%summarise(n=n())%>%
  mutate(prop=n/sum(n))
vis_barplot(tab,x = cut,y=prop,text = prop,
        col = cut,y_title = "Percentage",
        y_include = 0.45,y_breaks = scales::breaks_width(0.05),
        y_labels = function(x){scales::percent(x,accuracy = 1)})

```
